### ISSUE TITLE
How to pack all image to sprite atlas

### ISSUE THREAD

**Issue by takaaptech** [NicoleXiao/UIFramework#1]
Hi! @NicoleXiao 
I found your Framework is awesome to use, simple and fast.
How can I pack all the images to Sprite Atlas for reducing draw call ?
And after pack to Sprite Atlas, how we use it with Addressable ?
Thanks!

**Comment by NicoleXiao** [comment]
I'm writing this code.
I will upload the code in a while,please wait.
Thank you.
